#spring:
#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: 아이디@naver.com
#    password: 비밀번호
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com
#      mail.smtp.starttls.enable: true